### ISSUE TITLE
Question: Actor Directory info

### ISSUE THREAD

**Issue by AdrFax** [joshuaavalon/AvalonXmlAgent.bundle#2]
Hey there! I've been using this plug-in for quite a while, and it's worked great so far.

I write because I was interested in the "Actor Directory" option on the agent settings, but I couldn't find any info about it on the Wiki section, and I was hoping you could give me a brief description of how to use it.

**Comment by joshuaavalon** [comment]
It is not working right now. Just ignore it. See #1 for details.

**Comment by AdrFax** [comment]
Wow... I read through that thread before making this one, but I somehow missed the part that touched upon this matter. Thanks for the reply regardless.
