### ISSUE TITLE
Supported Protocols For Cast Images

### ISSUE THREAD

**Issue by delraykevin** [joshuaavalon/AvalonXmlAgent.bundle#5]
So I'm trying to add "cast" images for some family videos.

I have made it work by setting up IIS and serving them that way, but I'd prefer that they were just stored locally without having to fire up a web server.

Is that possible?

I have tried file:///<path to images>/imagename.jpg, etc, but just get empty spaces in Plex, or am I just barking up the wrong tree?

I'm going to go look at your code, but figured it would be good ask first...

**Comment by joshuaavalon** [comment]
You have to fork it and change the code. Here is how to load the image from local file.


https://github.com/joshuaavalon/AvalonXmlAgent.bundle/blob/41b4f1eca7d3db7718372d11b47c795b413c06cc/Contents/Code/helper.py#L190-L191

Since, I am no longer using this. I cannot provide more support.
