### ISSUE TITLE
How to add a line break / new line in the <plot> tag?

### ISSUE THREAD

**Issue by Cryborg12** [joshuaavalon/AvalonXmlAgent.bundle#7]
The title says it all. Is it even possible?

One more thing, is there a way to add an image carousel in the movie details page?

Thanks in advance :)

**Comment by joshuaavalon** [comment]
> The title says it all. Is it even possible?

Because it is just XML, you can search for how to add line break in XML. 

https://stackoverflow.com/questions/35504890/how-to-add-a-newline-line-break-in-xml-file

> One more thing, is there a way to add an image carousel in the movie details page?

If you mean image slideshow, then no. The metadata agent cannot control how plex display the data.
